# =======================
# AutoLearn: مثال إعدادات (Template)
# انسخ منها إلى config.yaml إذا احتجت
# =======================

goal: "تعلم أحدث طرق RAG والبحث الدلالي"
language: "ar"

# التحكم في سرعة وشِدّة التعلّم
max_cycles: 999999999
queries_per_cycle: 6
results_per_query: 8

# افضلية النتائج الحديثة + طول المقاطع
freshness_days: 540
min_chunk_len: 500
max_chunk_len: 1800

# عتبة الجِدّة لمنع التكرار (كلما ارتفعت قلّ التكرار)
novelty_threshold: 0.90

# عدد المقاطع التي تُقارن بها الجِدّة وتُستدعى وقت الإجابة
top_k_memory: 12

# قاعدة البيانات (يمكن تغييره إلى مجلد/مسار آخر)
db_path: "autolearn.db"

# وضع مُعزَّز (اختياري) — يتطلب مفاتيح:
# export OPENAI_API_KEY=...
# أو
# export GEMINI_API_KEY=...
llm:
  provider: "none"          # بدّلها إلى openai أو gemini لو فعّلت المفاتيح
  model: "gpt-4o-mini"      # أو "gemini-1.5-flash"
  temperature: 0.2
  max_tokens: 900

# سياسات أمان بسيطة
safety:
  blocked_domains:
    - "x.com"
    - "tiktok.com"
    - "facebook.com"
  respect_robots_txt: false
  max_page_bytes: 2000000
