language: "ar"
db_path: "/data/autolearn.db"

pace:
  interval_minutes: 10
  cycles_per_tick: 1

learning_keywords:
  - الذكاء الاصطناعي
  - تعلم الآلة
  - الشبكات
  - الاتصالات
  - بايثون
  - هندسة برمجيات

rss_feeds:
  - https://www.theverge.com/rss/index.xml
  - https://feeds.arstechnica.com/arstechnica/technology-lab
  - https://hnrss.org/frontpage

arxiv_queries:
  - cs.AI
  - cs.LG
  - cs.CL

trusted_domains:
  - wikipedia.org
  - arxiv.org
  - theverge.com
  - arstechnica.com
  - acm.org
  - ieee.org

blocked_domains:
  - x.com
  - tiktok.com
  - facebook.com

llm:
  provider: "none"
  model: "gpt-4o-mini"
  temperature: 0.2
  max_tokens: 900

safety:
  respect_robots_txt: true
  max_page_bytes: 2000000
  language: ar

personal_files_dir: /data/inbox
